Profiles page (multiple choice)
Teamable-Analytics/teamable-frontend pull request #22
Opened 2024-02-13 00:16 UTC by SanaBob

2024-02-13 05:26 UTC, Opeyem1a requested changes
Skimmed in review, but here's a video explaining my cryptic comments above
https://www.loom.com/share/d05b57101d8a41e5aad4296bdf615d1b

2024-02-13 05:26 UTC, Opeyem1a commented on src/app/profiles/multipleChoice/page.tsx
> +    const [, forceUpdate] = useReducer(x => x + 1, 0)
What is this?

2024-02-13 05:26 UTC, Opeyem1a commented on src/app/profiles/multipleChoice/page.tsx
> +    const SortableInput = ({answer, index}: {answer: Answer, index: number}) => {
Smells like the problem

2024-02-27 03:28 UTC, Opeyem1a requested changes
Most comments relate to formik usage, generally good use of the tools available to you to solve the problem, most of the work now is cleanup so it's more maintainable going forward

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                {/* EDITOR */}
nit;

does this comment really add value?

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                                            setAnswers([...answers, {id: answers.length + 1, label: ''}])
not a fan of `answers.length + 1`, not a strong way to guarantee uniqueness, assuming that's the goal. Not to mention, I'm not entirely sure what we're using the ids of each answer for?

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                                        }}>Save Question</Button>
this code has unlinted vibes btw

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                    {/* VIEWER */}
if these comments denote different sections, I prefer the pattern of just defining another component like `<Viewer />` / `<Editor />` to improve the readability there. If you use Formik contexts fully this shouldn't be an issue and you won't even need to prop drill

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +            <Label>Answer {index + 1}</Label>
nit;

UI-wise, I'm unconvinced that we need a label for each answer option here

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                                setAnswers(answers.map(el => {
why set answers as a state and then also st the formik field value?

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
> +                                setFieldValue(`answers.${index}`, e.target.value)
I think there's a cooler way to do this by using `useField()` and what it returns instead of `setFieldValue` directly

2024-02-27 03:28 UTC, Opeyem1a commented on src/app/profiles/multipleChoiceEditor.tsx
Rename to `MultipleChoiceEditor.tsx` for consistency.

I also think you should make a `(components)` folder in `/profiles` and put this component inside there

2024-03-04 04:31 UTC, Opeyem1a approved these changes
Approving because my comments are nitpicks.
You technically don't need to fix them to merge but read them

2024-03-04 04:31 UTC, Opeyem1a commented on next.config.js
> +const nextConfig = {
nice

2024-03-04 04:31 UTC, Opeyem1a commented on src/app/profiles/page.tsx
> +// Only have Multiple Choice Editor for now
nit;

not a valuable comment

2024-03-04 04:31 UTC, Opeyem1a commented on src/app/profiles/(components)/MultipleChoiceComponent.tsx
> +const INITIAL_VALUES = {
kinda-nit;

these would most likely be passed in to `<MultipleChoiceComponent />` from some upper component that retrieved them from the db.

I would just define our fake initial values directly within `<MultipleChoiceComponent />` for now

2024-03-04 04:31 UTC, Opeyem1a commented on src/app/profiles/(components)/MultipleChoiceComponent.tsx
> +                    <Input name="question" type="text" onChange={handleChange} placeholder="Question Text" defaultValue={INITIAL_QUESTION} />
I don't think we need `defaultValue` here, it's not going to be able to work like this once you have to actually use real data here.

If you 100% must define it, I think there's a way to get it from formik's context

2024-03-04 07:30 UTC, SanaBob commented
> Approving because my comments are nitpicks. You technically don't need to fix them to merge but read them

I will address these comments in the next pr

2024-03-04 07:30 UTC, merged